/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Event, EventInterface } from "../Event";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Borrow",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061020b806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630c28d13e14610030575b600080fd5b61004a6004803603810190610045919061013b565b61004c565b005b3373ffffffffffffffffffffffffffffffffffffffff16837ff9a33434428db5f0416c03e38307599ad0b9b9965d6c070eb08e87cc1f0ca50e84846040516100959291906101ac565b60405180910390a3505050565b600080fd5b6000819050919050565b6100ba816100a7565b81146100c557600080fd5b50565b6000813590506100d7816100b1565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610108826100dd565b9050919050565b610118816100fd565b811461012357600080fd5b50565b6000813590506101358161010f565b92915050565b600080600060608486031215610154576101536100a2565b5b6000610162868287016100c8565b935050602061017386828701610126565b9250506040610184868287016100c8565b9150509250925092565b610197816100fd565b82525050565b6101a6816100a7565b82525050565b60006040820190506101c1600083018561018e565b6101ce602083018461019d565b939250505056fea2646970667358221220cd8402176292000d6dac177f735fae5ed314e6a92559ae4104e4dca17843504164736f6c63430008130033";

type EventConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Event__factory extends ContractFactory {
  constructor(...args: EventConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Event & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Event__factory {
    return super.connect(runner) as Event__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventInterface {
    return new Interface(_abi) as EventInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Event {
    return new Contract(address, _abi, runner) as unknown as Event;
  }
}
