/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface Function2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDouble"
      | "getDoubleA"
      | "getDoubleA2"
      | "printDouble"
      | "pureFunction"
      | "viewFunction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getDouble",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDoubleA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDoubleA2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "printDouble",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pureFunction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewFunction",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getDouble", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDoubleA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDoubleA2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "printDouble",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pureFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewFunction",
    data: BytesLike
  ): Result;
}

export interface Function2 extends BaseContract {
  connect(runner?: ContractRunner | null): Function2;
  waitForDeployment(): Promise<this>;

  interface: Function2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDouble: TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, bigint] & { a: bigint; b: bigint }],
    "view"
  >;

  getDoubleA: TypedContractMethod<[_a: BigNumberish], [bigint], "view">;

  getDoubleA2: TypedContractMethod<[_a: BigNumberish], [bigint], "view">;

  printDouble: TypedContractMethod<[], [void], "view">;

  pureFunction: TypedContractMethod<[a: BigNumberish], [void], "view">;

  viewFunction: TypedContractMethod<[a: BigNumberish], [void], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDouble"
  ): TypedContractMethod<
    [_a: BigNumberish, _b: BigNumberish],
    [[bigint, bigint] & { a: bigint; b: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDoubleA"
  ): TypedContractMethod<[_a: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDoubleA2"
  ): TypedContractMethod<[_a: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "printDouble"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "pureFunction"
  ): TypedContractMethod<[a: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "viewFunction"
  ): TypedContractMethod<[a: BigNumberish], [void], "view">;

  filters: {};
}
