/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface Function1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "externalFunction"
      | "function1"
      | "publicFunction"
      | "stateValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "externalFunction",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "function1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateValue",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "externalFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "function1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stateValue", data: BytesLike): Result;
}

export interface Function1 extends BaseContract {
  connect(runner?: ContractRunner | null): Function1;
  waitForDeployment(): Promise<this>;

  interface: Function1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  externalFunction: TypedContractMethod<[], [void], "nonpayable">;

  function1: TypedContractMethod<[], [void], "nonpayable">;

  publicFunction: TypedContractMethod<[], [void], "nonpayable">;

  stateValue: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "externalFunction"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "function1"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "publicFunction"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stateValue"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
