/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VariableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addressValue"
      | "byteValue"
      | "defaultAddressValue"
      | "defaultByteValue"
      | "defaultValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addressValue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "byteValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultAddressValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultByteValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultValue",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addressValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "byteValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultAddressValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultByteValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultValue",
    data: BytesLike
  ): Result;
}

export interface Variable extends BaseContract {
  connect(runner?: ContractRunner | null): Variable;
  waitForDeployment(): Promise<this>;

  interface: VariableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addressValue: TypedContractMethod<[], [string], "view">;

  byteValue: TypedContractMethod<[], [string], "view">;

  defaultAddressValue: TypedContractMethod<[], [string], "view">;

  defaultByteValue: TypedContractMethod<[], [string], "view">;

  defaultValue: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addressValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "byteValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultAddressValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultByteValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultValue"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
